// Generates js/preflop.js: the 169 starting hands ranked by Monte-Carlo equity vs 2 random hands.
import { writeFileSync } from 'fs';
import { estimateEquity } from '../js/bot.js';
const R = '23456789TJQKA';
const hands = [];
for (let i = 12; i >= 0; i--) for (let j = i; j >= 0; j--) {
  if (i === j) hands.push({ key: R[i] + R[j], cards: [i * 4, j * 4 + 1], combos: 6 });
  else {
    hands.push({ key: R[i] + R[j] + 's', cards: [i * 4, j * 4], combos: 4 });
    hands.push({ key: R[i] + R[j] + 'o', cards: [i * 4, j * 4 + 1], combos: 12 });
  }
}
for (const h of hands) h.eq = estimateEquity(h.cards, [], 2, 40000);
hands.sort((a, b) => b.eq - a.eq);
writeFileSync(new URL('../js/preflop.js', import.meta.url), `// Generated by tools/gen-preflop.mjs: starting hands from best to worst (equity vs 2 random hands).\nexport const PREFLOP_ORDER = ${JSON.stringify(hands.map((h) => h.key))};\n`);
console.log(hands.slice(0, 12).map((h) => h.key + ':' + h.eq.toFixed(3)).join(' '), '...', hands.slice(-5).map((h) => h.key).join(' '));
